import type { Product, ProductCategory } from "./storeTypes";

export type { Product, ProductCategory } from "./storeTypes";

const rankGroups = {
  VIP: "vip",
  NEMESIS: "nemesis",
  APEX: "apex",
  VORTEX: "vortex",
  EON: "eon",
  OBLIVION: "oblivion",
  ZENITH: "zenith",
  NYX: "nyx",
  BROTHERS: "brothers",
  "BROTHERS+": "brothersplus",
} as const;

function rankDelivery(name: keyof typeof rankGroups) {
  return [`lp user %player% group add ${rankGroups[name]}`];
}

const rankProducts: Product[] = [
  {
    id: "rank_vip",
    category: "rank",
    name: "VIP",
    description: "Primer rango permanente con comandos esenciales y recursos iniciales.",
    priceUsd: 1,
    badge: "Inicio",
    gradientClass: "from-emerald-400/24 via-lime-300/14 to-transparent",
    theme: {
      accent: "#22c55e",
      accent2: "#9eff3f",
      text: "#d8ff75",
      glow: "rgba(34, 197, 94, 0.36)",
      mark: "VIP",
    },
    visual: { kind: "rank", label: "VIP", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "VIP" },
      { label: "Multiplicador", value: "x2.0" },
      { label: "Descuento RankUP", value: "5%" },
      { label: "Armor Boost", value: "+0.1%" },
      { label: "Parcelas", value: "2" },
    ],
    rewards: [
      "Gemas: 30M",
      "Tokens: 50M",
      "Esencias: 100K",
      "Bombas: x6 Common",
      "Lootboxes: x1 Basic",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick"],
    deliveryCommands: rankDelivery("VIP"),
    perks: ["Tag VIP", "Multiplicador x2.0", "Rango permanente"],
  },
  {
    id: "rank_nemesis",
    category: "rank",
    name: "NEMESIS",
    description: "Mas progreso, mas parcelas y acceso a mesa de trabajo donde estes.",
    priceUsd: 4,
    badge: "Popular",
    gradientClass: "from-cyan-400/24 via-teal-300/14 to-transparent",
    theme: {
      accent: "#19e6e6",
      accent2: "#80fff5",
      text: "#b7fffb",
      glow: "rgba(25, 230, 230, 0.34)",
      mark: "NE",
    },
    visual: { kind: "rank", label: "NEMESIS", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "NEMESIS" },
      { label: "Multiplicador", value: "x3.0" },
      { label: "Descuento RankUP", value: "8%" },
      { label: "Armor Boost", value: "+0.3%" },
      { label: "Parcelas", value: "4" },
    ],
    rewards: [
      "Gemas: 60M",
      "Tokens: 100M",
      "Esencias: 200K",
      "Bombas: x8 Common",
      "Lootboxes: x2 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/workbench"],
    deliveryCommands: rankDelivery("NEMESIS"),
    perks: ["Tag NEMESIS", "Multiplicador x3.0", "Incluye /workbench"],
  },
  {
    id: "rank_apex",
    category: "rank",
    name: "APEX",
    description: "Rango azul con mejor boost, mas recursos y reparacion rapida.",
    priceUsd: 7.5,
    badge: "Mejor mejora",
    gradientClass: "from-blue-500/24 via-sky-300/14 to-transparent",
    theme: {
      accent: "#2589ff",
      accent2: "#63c8ff",
      text: "#c5e7ff",
      glow: "rgba(37, 137, 255, 0.36)",
      mark: "AX",
    },
    visual: { kind: "rank", label: "APEX", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "APEX" },
      { label: "Multiplicador", value: "x4.0" },
      { label: "Descuento RankUP", value: "11%" },
      { label: "Armor Boost", value: "+0.5%" },
      { label: "Parcelas", value: "6" },
    ],
    rewards: [
      "Gemas: 90M",
      "Tokens: 150M",
      "Esencias: 300K",
      "Bombas: x10 Common",
      "Lootboxes: x3 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/repair"],
    deliveryCommands: rankDelivery("APEX"),
    perks: ["Tag APEX", "Multiplicador x4.0", "Incluye /repair"],
  },
  {
    id: "rank_vortex",
    category: "rank",
    name: "VORTEX",
    description: "Rango magenta con reparacion completa y recursos de alto valor.",
    priceUsd: 12,
    badge: "Avanzado",
    gradientClass: "from-fuchsia-500/24 via-pink-400/14 to-transparent",
    theme: {
      accent: "#ff31d0",
      accent2: "#ff88ed",
      text: "#ffd1f7",
      glow: "rgba(255, 49, 208, 0.34)",
      mark: "VX",
    },
    visual: { kind: "rank", label: "VORTEX", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "VORTEX" },
      { label: "Multiplicador", value: "x5.0" },
      { label: "Descuento RankUP", value: "14%" },
      { label: "Armor Boost", value: "+0.7%" },
      { label: "Parcelas", value: "8" },
    ],
    rewards: [
      "Gemas: 120M",
      "Tokens: 200M",
      "Esencias: 400K",
      "Bombas: x12 Rare",
      "Lootboxes: x4 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/repair all"],
    deliveryCommands: rankDelivery("VORTEX"),
    perks: ["Tag VORTEX", "Multiplicador x5.0", "Incluye /repair all"],
  },
  {
    id: "rank_eon",
    category: "rank",
    name: "EON",
    description: "Un rango verde premium con mas economia, parcelas y condensado.",
    priceUsd: 14.99,
    badge: "Premium",
    gradientClass: "from-lime-400/24 via-green-300/14 to-transparent",
    theme: {
      accent: "#8aff00",
      accent2: "#d7ff70",
      text: "#e8ffc0",
      glow: "rgba(138, 255, 0, 0.3)",
      mark: "EO",
    },
    visual: { kind: "rank", label: "EON", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "EON" },
      { label: "Multiplicador", value: "x6.0" },
      { label: "Descuento RankUP", value: "17%" },
      { label: "Armor Boost", value: "+0.9%" },
      { label: "Parcelas", value: "10" },
    ],
    rewards: [
      "Gemas: 150M",
      "Tokens: 250M",
      "Esencias: 500K",
      "Bombas: x14 Rare",
      "Lootboxes: x5 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/condense"],
    deliveryCommands: rankDelivery("EON"),
    perks: ["Tag EON", "Multiplicador x6.0", "Incluye /condense"],
  },
  {
    id: "rank_oblivion",
    category: "rank",
    name: "OBLIVION",
    description: "Rango dorado para jugadores que quieren recursos epic y /near.",
    priceUsd: 20,
    badge: "Elite",
    gradientClass: "from-amber-400/24 via-yellow-300/14 to-transparent",
    theme: {
      accent: "#ffb020",
      accent2: "#ffe66f",
      text: "#fff2b8",
      glow: "rgba(255, 176, 32, 0.34)",
      mark: "OB",
    },
    visual: { kind: "rank", label: "OBLIVION", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "OBLIVION" },
      { label: "Multiplicador", value: "x7.0" },
      { label: "Descuento RankUP", value: "20%" },
      { label: "Armor Boost", value: "+1.1%" },
      { label: "Parcelas", value: "12" },
    ],
    rewards: [
      "Gemas: 180M",
      "Tokens: 300M",
      "Esencias: 600K",
      "Bombas: x12 Epic",
      "Lootboxes: x6 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/near"],
    deliveryCommands: rankDelivery("OBLIVION"),
    perks: ["Tag OBLIVION", "Multiplicador x7.0", "Incluye /near"],
  },
  {
    id: "rank_zenith",
    category: "rank",
    name: "ZENITH",
    description: "Rango celeste con boost alto, recompensas epic y comando /stack.",
    priceUsd: 26,
    badge: "Alto nivel",
    gradientClass: "from-cyan-300/24 via-sky-500/14 to-transparent",
    theme: {
      accent: "#27d8ff",
      accent2: "#84f4ff",
      text: "#d3fbff",
      glow: "rgba(39, 216, 255, 0.34)",
      mark: "ZN",
    },
    visual: { kind: "rank", label: "ZENITH", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "ZENITH" },
      { label: "Multiplicador", value: "x8.0" },
      { label: "Descuento RankUP", value: "23%" },
      { label: "Armor Boost", value: "+1.3%" },
      { label: "Parcelas", value: "14" },
    ],
    rewards: [
      "Gemas: 210M",
      "Tokens: 350M",
      "Esencias: 700K",
      "Bombas: x14 Epic",
      "Lootboxes: x7 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/stack"],
    deliveryCommands: rankDelivery("ZENITH"),
    perks: ["Tag ZENITH", "Multiplicador x8.0", "Incluye /stack"],
  },
  {
    id: "rank_nyx",
    category: "rank",
    name: "NYX",
    description: "Rango rojo oscuro con chat color, mas parcelas y recompensas epic.",
    priceUsd: 31.99,
    badge: "Exclusivo",
    gradientClass: "from-red-600/24 via-rose-500/14 to-transparent",
    theme: {
      accent: "#ef2b2b",
      accent2: "#ff7a70",
      text: "#ffd0cc",
      glow: "rgba(239, 43, 43, 0.34)",
      mark: "NX",
    },
    visual: { kind: "rank", label: "NYX", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "NYX" },
      { label: "Multiplicador", value: "x9.0" },
      { label: "Descuento RankUP", value: "26%" },
      { label: "Armor Boost", value: "+1.5%" },
      { label: "Parcelas", value: "16" },
    ],
    rewards: [
      "Gemas: 240M",
      "Tokens: 400M",
      "Esencias: 800K",
      "Bombas: x18 Epic",
      "Lootboxes: x8 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/chatcolor"],
    deliveryCommands: rankDelivery("NYX"),
    perks: ["Tag NYX", "Multiplicador x9.0", "Incluye /chatcolor"],
  },
  {
    id: "rank_brothers",
    category: "rank",
    name: "BROTHERS",
    description: "Rango dorado superior con multiplicador x10 y recompensas mythic.",
    priceUsd: 40,
    badge: "Top",
    gradientClass: "from-yellow-300/24 via-amber-400/14 to-transparent",
    theme: {
      accent: "#ffd84d",
      accent2: "#fff3a3",
      text: "#fff8cf",
      glow: "rgba(255, 216, 77, 0.34)",
      mark: "BR",
    },
    visual: { kind: "rank", label: "BROTHERS", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "BROTHERS" },
      { label: "Multiplicador", value: "x10.0" },
      { label: "Descuento RankUP", value: "29%" },
      { label: "Armor Boost", value: "+1.7%" },
      { label: "Parcelas", value: "18" },
    ],
    rewards: [
      "Gemas: 270M",
      "Tokens: 450M",
      "Esencias: 900K",
      "Bombas: x16 Mythic",
      "Lootboxes: x9 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/chatcolor"],
    deliveryCommands: rankDelivery("BROTHERS"),
    perks: ["Tag BROTHERS", "Multiplicador x10.0", "Bombas Mythic"],
  },
  {
    id: "rank_brothers_plus",
    category: "rank",
    name: "BROTHERS+",
    description: "El rango maximo: todos los cosmeticos, prioridad y paquete legendario.",
    priceUsd: 59.99,
    badge: "Maximo",
    gradientClass: "from-red-500/26 via-orange-400/16 to-transparent",
    theme: {
      accent: "#ff4a35",
      accent2: "#ffb26b",
      text: "#ffe0d8",
      glow: "rgba(255, 74, 53, 0.36)",
      mark: "B+",
    },
    visual: { kind: "rank", label: "BROTHERS+", detail: "Permanente" },
    stats: [
      { label: "Tag", value: "BROTHERS+" },
      { label: "Multiplicador", value: "x11.0" },
      { label: "Descuento RankUP", value: "32%" },
      { label: "Armor Boost", value: "+1.9%" },
      { label: "Parcelas", value: "20" },
    ],
    rewards: [
      "Gemas: 300M",
      "Tokens: 500M",
      "Esencias: 1M",
      "Bombas: x32 Legendary",
      "Lootboxes: x12 Premium",
    ],
    commands: [
      "Incluye todos los comandos anteriores",
      "Cosmeticos /uc desbloqueados",
      "Color de chat /chatcolor",
      "Prioridad para entrar con servidor lleno",
    ],
    deliveryCommands: rankDelivery("BROTHERS+"),
    perks: ["Tag BROTHERS+", "Multiplicador x11.0", "Todo desbloqueado"],
  },
];

const crateProducts: Product[] = [
  {
    id: "crate_brothers_x7",
    category: "crate",
    name: "Llave BROTHERS x7",
    description: "Pack de 7 llaves BROTHERS para reclamar la crate dentro del servidor.",
    priceUsd: 14.99,
    badge: "Llave premium",
    gradientClass: "from-orange-400/28 via-yellow-300/18 to-transparent",
    theme: {
      accent: "#ff9f1c",
      accent2: "#ffe066",
      text: "#fff1b8",
      glow: "rgba(255, 159, 28, 0.36)",
      mark: "K7",
    },
    visual: { kind: "crate", label: "BROTHERS", detail: "x7 llaves" },
    rewards: ["7 llaves BROTHERS", "Crate premium del servidor", "Entrega automatica al usuario"],
    deliveryCommands: ["crate give p Brothers 7 %player%"],
  },
];

const exclusiveProducts: Product[] = [
  {
    id: "exclusive_bundle_super_x10",
    category: "exclusive",
    name: "Bundle SUPER x10",
    description: "Diez bundles SUPER con recursos fuertes y multiplicador temporal.",
    priceUsd: 25,
    badge: "Bundle",
    featured: true,
    gradientClass: "from-yellow-300/24 via-orange-400/18 to-transparent",
    theme: {
      accent: "#ffcc33",
      accent2: "#ff8a00",
      text: "#fff1b8",
      glow: "rgba(255, 204, 51, 0.34)",
      mark: "S",
    },
    visual: { kind: "bundle", label: "SUPER", detail: "x10 bundles" },
    rewards: [
      "Multiplicador +10.0 por 15 min",
      "Dinero: $1B",
      "Tokens: 5B",
      "Gemas: 5M",
      "Esencias: 5M",
      "Puntos gang: +5 por jugador",
    ],
    deliveryCommands: ["kit give bundle5 %player%"],
  },
  {
    id: "exclusive_premium_lootbox_x24",
    category: "exclusive",
    name: "Premium Lootbox x24",
    description: "Pack de 24 lootboxes premium con premios reales y cooldown rapido.",
    priceUsd: 13.99,
    badge: "Lootbox",
    gradientClass: "from-purple-500/24 via-cyan-400/14 to-transparent",
    theme: {
      accent: "#8b5cf6",
      accent2: "#22d3ee",
      text: "#e9d5ff",
      glow: "rgba(139, 92, 246, 0.34)",
      mark: "LB",
    },
    visual: { kind: "lootbox", label: "PREMIUM", detail: "x24 lootboxes" },
    rewards: [
      "Incluye gemas, tokens, esencias y dinero",
      "Entrega entre 4 y 10 premios reales",
      "Cooldown de apertura: 1 segundo",
      "Pack total: x24 Premium Lootbox",
    ],
    deliveryCommands: ["lootbox give %player% Premium 24"],
  },
  {
    id: "exclusive_boosteritem_x1",
    category: "exclusive",
    name: "BoosterItem x1",
    description: "Mejora permanente para armadura y economias del servidor.",
    priceUsd: 3.99,
    badge: "Booster",
    gradientClass: "from-orange-500/24 via-red-400/14 to-transparent",
    theme: {
      accent: "#ff6b35",
      accent2: "#ffd166",
      text: "#ffe4c7",
      glow: "rgba(255, 107, 53, 0.34)",
      mark: "1%",
    },
    visual: { kind: "booster", label: "BOOSTER", detail: "+1%" },
    rewards: [
      "+1% de mejora para tu armadura",
      "+1% de ganancias en todas las economias disponibles",
      "Se aplica desde el item dentro del servidor",
    ],
    deliveryCommands: ["armadura give %player% boosteritem 1"],
  },
  {
    id: "exclusive_azada_xp_500k",
    category: "exclusive",
    name: "XP Azada 500K",
    description: "Aumenta la experiencia de tu azada para subir niveles mucho mas rapido.",
    priceUsd: 9.99,
    badge: "Progreso",
    gradientClass: "from-lime-400/24 via-emerald-400/14 to-transparent",
    theme: {
      accent: "#a3e635",
      accent2: "#34d399",
      text: "#ecfccb",
      glow: "rgba(163, 230, 53, 0.34)",
      mark: "XP",
    },
    visual: { kind: "xp", label: "AZADA", detail: "500K XP" },
    rewards: [
      "500.000 XP para tu azada",
      "Sube niveles mas rapido",
      "Ideal para progresar en farmeo",
    ],
    deliveryCommands: ["azada add %player% 500000"],
  },
  {
    id: "exclusive_money_multiplier_20x",
    category: "exclusive",
    name: "Multiplicador de Dinero 20x",
    description: "Multiplicador permanente de dinero para mejorar tus ganancias del servidor.",
    priceUsd: 13.99,
    badge: "Permanente",
    gradientClass: "from-emerald-400/24 via-yellow-300/14 to-transparent",
    theme: {
      accent: "#22c55e",
      accent2: "#facc15",
      text: "#dcfce7",
      glow: "rgba(34, 197, 94, 0.32)",
      mark: "20x",
    },
    visual: { kind: "money", label: "DINERO", detail: "20x permanente" },
    rewards: [
      "20x multiplicador de dinero permanente",
      "Mejora las ganancias economicas",
      "Se aplica al jugador dentro del servidor",
    ],
    deliveryCommands: ["Multiplier set Permanent 20.0 %player%"],
  },
  {
    id: "exclusive_ultracosmetics_access",
    category: "exclusive",
    name: "Acceso UltraCosmetics",
    description: "Acceso total a /uc y /ultracosmetics con todos los cosmeticos desbloqueados.",
    priceUsd: 9.99,
    badge: "Cosmeticos",
    gradientClass: "from-pink-500/24 via-violet-500/14 to-transparent",
    theme: {
      accent: "#ec4899",
      accent2: "#a855f7",
      text: "#fce7f3",
      glow: "rgba(236, 72, 153, 0.34)",
      mark: "UC",
    },
    visual: { kind: "cosmetics", label: "COSMETICS", detail: "all access" },
    rewards: [
      "Acceso al comando /uc",
      "Cosmeticos, mascotas y gadgets",
      "Emotes, sombreros, efectos y particulas",
      "Efectos de proyectiles y efectos al morir",
    ],
    deliveryCommands: ["lp user %player% permission set ultracosmetics.allcosmetics"],
  },
];

export const catalog: Product[] = [
  ...rankProducts,
  ...crateProducts,
  ...exclusiveProducts,
];

export function formatUsd(amount: number) {
  const formatted = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 2,
  }).format(amount);

  return `${formatted} USD`;
}

export function getProductPriceLabel(product: Product) {
  return product.priceLabel ?? formatUsd(product.priceUsd);
}

export function getProductById(id: string) {
  return catalog.find((product) => product.id === id) ?? null;
}

export function getProductsByCategory(category: ProductCategory) {
  return catalog.filter((product) => product.category === category);
}

export function getFeaturedProduct() {
  return catalog.find((product) => product.featured) ?? exclusiveProducts[0];
}
