import type { Product, ProductCategory } from "./storeTypes";

export type { Product, ProductCategory } from "./storeTypes";

const rankProducts: Product[] = [
  {
    id: "rank_vip",
    category: "rank",
    name: "VIP",
    description: "Primer rango permanente con comandos esenciales y recursos iniciales.",
    priceUsd: 1,
    badge: "Inicio",
    gradientClass: "from-emerald-400/24 via-lime-300/14 to-transparent",
    theme: {
      accent: "#22c55e",
      accent2: "#9eff3f",
      text: "#d8ff75",
      glow: "rgba(34, 197, 94, 0.36)",
      mark: "VIP",
    },
    stats: [
      { label: "Tag", value: "VIP" },
      { label: "Multiplicador", value: "x2.0" },
      { label: "Descuento RankUP", value: "5%" },
      { label: "Armor Boost", value: "+0.1%" },
      { label: "Parcelas", value: "2" },
    ],
    rewards: [
      "Gemas: 30M",
      "Tokens: 50M",
      "Esencias: 100K",
      "Bombas: x6 Common",
      "Lootboxes: x1 Basic",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick"],
    perks: ["Tag VIP", "Multiplicador x2.0", "5 recursos al comprar"],
  },
  {
    id: "rank_nemesis",
    category: "rank",
    name: "NEMESIS",
    description: "Mas progreso, mas parcelas y acceso a mesa de trabajo donde estes.",
    priceUsd: 4,
    badge: "Popular",
    gradientClass: "from-cyan-400/24 via-teal-300/14 to-transparent",
    theme: {
      accent: "#19e6e6",
      accent2: "#80fff5",
      text: "#b7fffb",
      glow: "rgba(25, 230, 230, 0.34)",
      mark: "NE",
    },
    stats: [
      { label: "Tag", value: "NEMESIS" },
      { label: "Multiplicador", value: "x3.0" },
      { label: "Descuento RankUP", value: "8%" },
      { label: "Armor Boost", value: "+0.3%" },
      { label: "Parcelas", value: "4" },
    ],
    rewards: [
      "Gemas: 60M",
      "Tokens: 100M",
      "Esencias: 200K",
      "Bombas: x8 Common",
      "Lootboxes: x2 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/workbench"],
    perks: ["Tag NEMESIS", "Multiplicador x3.0", "Incluye /workbench"],
  },
  {
    id: "rank_apex",
    category: "rank",
    name: "APEX",
    description: "Rango azul con mejor boost, mas recursos y reparacion rapida.",
    priceUsd: 7.5,
    badge: "Mejor mejora",
    gradientClass: "from-blue-500/24 via-sky-300/14 to-transparent",
    theme: {
      accent: "#2589ff",
      accent2: "#63c8ff",
      text: "#c5e7ff",
      glow: "rgba(37, 137, 255, 0.36)",
      mark: "AX",
    },
    stats: [
      { label: "Tag", value: "APEX" },
      { label: "Multiplicador", value: "x4.0" },
      { label: "Descuento RankUP", value: "11%" },
      { label: "Armor Boost", value: "+0.5%" },
      { label: "Parcelas", value: "6" },
    ],
    rewards: [
      "Gemas: 90M",
      "Tokens: 150M",
      "Esencias: 300K",
      "Bombas: x10 Common",
      "Lootboxes: x3 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/repair"],
    perks: ["Tag APEX", "Multiplicador x4.0", "Incluye /repair"],
  },
  {
    id: "rank_vortex",
    category: "rank",
    name: "VORTEX",
    description: "Rango magenta con reparacion completa y recursos de alto valor.",
    priceUsd: 12,
    badge: "Avanzado",
    gradientClass: "from-fuchsia-500/24 via-pink-400/14 to-transparent",
    theme: {
      accent: "#ff31d0",
      accent2: "#ff88ed",
      text: "#ffd1f7",
      glow: "rgba(255, 49, 208, 0.34)",
      mark: "VX",
    },
    stats: [
      { label: "Tag", value: "VORTEX" },
      { label: "Multiplicador", value: "x5.0" },
      { label: "Descuento RankUP", value: "14%" },
      { label: "Armor Boost", value: "+0.7%" },
      { label: "Parcelas", value: "8" },
    ],
    rewards: [
      "Gemas: 120M",
      "Tokens: 200M",
      "Esencias: 400K",
      "Bombas: x12 Rare",
      "Lootboxes: x4 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/repair all"],
    perks: ["Tag VORTEX", "Multiplicador x5.0", "Incluye /repair all"],
  },
  {
    id: "rank_eon",
    category: "rank",
    name: "EON",
    description: "Un rango verde premium con mas economia, parcelas y condensado.",
    priceUsd: 14.99,
    badge: "Premium",
    gradientClass: "from-lime-400/24 via-green-300/14 to-transparent",
    theme: {
      accent: "#8aff00",
      accent2: "#d7ff70",
      text: "#e8ffc0",
      glow: "rgba(138, 255, 0, 0.3)",
      mark: "EO",
    },
    stats: [
      { label: "Tag", value: "EON" },
      { label: "Multiplicador", value: "x6.0" },
      { label: "Descuento RankUP", value: "17%" },
      { label: "Armor Boost", value: "+0.9%" },
      { label: "Parcelas", value: "10" },
    ],
    rewards: [
      "Gemas: 150M",
      "Tokens: 250M",
      "Esencias: 500K",
      "Bombas: x14 Rare",
      "Lootboxes: x5 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/condense"],
    perks: ["Tag EON", "Multiplicador x6.0", "Incluye /condense"],
  },
  {
    id: "rank_oblivion",
    category: "rank",
    name: "OBLIVION",
    description: "Rango dorado para jugadores que quieren recursos epic y /near.",
    priceUsd: 20,
    badge: "Elite",
    gradientClass: "from-amber-400/24 via-yellow-300/14 to-transparent",
    theme: {
      accent: "#ffb020",
      accent2: "#ffe66f",
      text: "#fff2b8",
      glow: "rgba(255, 176, 32, 0.34)",
      mark: "OB",
    },
    stats: [
      { label: "Tag", value: "OBLIVION" },
      { label: "Multiplicador", value: "x7.0" },
      { label: "Descuento RankUP", value: "20%" },
      { label: "Armor Boost", value: "+1.1%" },
      { label: "Parcelas", value: "12" },
    ],
    rewards: [
      "Gemas: 180M",
      "Tokens: 300M",
      "Esencias: 600K",
      "Bombas: x12 Epic",
      "Lootboxes: x6 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/near"],
    perks: ["Tag OBLIVION", "Multiplicador x7.0", "Incluye /near"],
  },
  {
    id: "rank_zenith",
    category: "rank",
    name: "ZENITH",
    description: "Rango celeste con boost alto, recompensas epic y comando /stack.",
    priceUsd: 26,
    badge: "Alto nivel",
    gradientClass: "from-cyan-300/24 via-sky-500/14 to-transparent",
    theme: {
      accent: "#27d8ff",
      accent2: "#84f4ff",
      text: "#d3fbff",
      glow: "rgba(39, 216, 255, 0.34)",
      mark: "ZN",
    },
    stats: [
      { label: "Tag", value: "ZENITH" },
      { label: "Multiplicador", value: "x8.0" },
      { label: "Descuento RankUP", value: "23%" },
      { label: "Armor Boost", value: "+1.3%" },
      { label: "Parcelas", value: "14" },
    ],
    rewards: [
      "Gemas: 210M",
      "Tokens: 350M",
      "Esencias: 700K",
      "Bombas: x14 Epic",
      "Lootboxes: x7 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/stack"],
    perks: ["Tag ZENITH", "Multiplicador x8.0", "Incluye /stack"],
  },
  {
    id: "rank_nyx",
    category: "rank",
    name: "NYX",
    description: "Rango rojo oscuro con chat color, mas parcelas y recompensas epic.",
    priceUsd: 31.99,
    badge: "Exclusivo",
    gradientClass: "from-red-600/24 via-rose-500/14 to-transparent",
    theme: {
      accent: "#ef2b2b",
      accent2: "#ff7a70",
      text: "#ffd0cc",
      glow: "rgba(239, 43, 43, 0.34)",
      mark: "NX",
    },
    stats: [
      { label: "Tag", value: "NYX" },
      { label: "Multiplicador", value: "x9.0" },
      { label: "Descuento RankUP", value: "26%" },
      { label: "Armor Boost", value: "+1.5%" },
      { label: "Parcelas", value: "16" },
    ],
    rewards: [
      "Gemas: 240M",
      "Tokens: 400M",
      "Esencias: 800K",
      "Bombas: x18 Epic",
      "Lootboxes: x8 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/chatcolor"],
    perks: ["Tag NYX", "Multiplicador x9.0", "Incluye /chatcolor"],
  },
  {
    id: "rank_brothers",
    category: "rank",
    name: "BROTHERS",
    description: "Rango dorado superior con multiplicador x10 y recompensas mythic.",
    priceUsd: 40,
    badge: "Top",
    gradientClass: "from-yellow-300/24 via-amber-400/14 to-transparent",
    theme: {
      accent: "#ffd84d",
      accent2: "#fff3a3",
      text: "#fff8cf",
      glow: "rgba(255, 216, 77, 0.34)",
      mark: "BR",
    },
    stats: [
      { label: "Tag", value: "BROTHERS" },
      { label: "Multiplicador", value: "x10.0" },
      { label: "Descuento RankUP", value: "29%" },
      { label: "Armor Boost", value: "+1.7%" },
      { label: "Parcelas", value: "18" },
    ],
    rewards: [
      "Gemas: 270M",
      "Tokens: 450M",
      "Esencias: 900K",
      "Bombas: x16 Mythic",
      "Lootboxes: x9 Premium",
    ],
    commands: ["/feed", "/fly", "/ec", "/invsee", "/nick", "/chatcolor"],
    perks: ["Tag BROTHERS", "Multiplicador x10.0", "Bombas Mythic"],
  },
  {
    id: "rank_brothers_plus",
    category: "rank",
    name: "BROTHERS+",
    description: "El rango maximo: todos los cosmeticos, prioridad y paquete legendario.",
    priceUsd: 59.99,
    badge: "Maximo",
    gradientClass: "from-red-500/26 via-orange-400/16 to-transparent",
    theme: {
      accent: "#ff4a35",
      accent2: "#ffb26b",
      text: "#ffe0d8",
      glow: "rgba(255, 74, 53, 0.36)",
      mark: "B+",
    },
    stats: [
      { label: "Tag", value: "BROTHERS+" },
      { label: "Multiplicador", value: "x11.0" },
      { label: "Descuento RankUP", value: "32%" },
      { label: "Armor Boost", value: "+1.9%" },
      { label: "Parcelas", value: "20" },
    ],
    rewards: [
      "Gemas: 300M",
      "Tokens: 500M",
      "Esencias: 1M",
      "Bombas: x32 Legendary",
      "Lootboxes: x12 Premium",
    ],
    commands: [
      "Incluye todos los comandos anteriores",
      "Cosmeticos /uc desbloqueados",
      "Color de chat /chatcolor",
      "Prioridad para entrar con servidor lleno",
    ],
    perks: ["Tag BROTHERS+", "Multiplicador x11.0", "Todo desbloqueado"],
  },
];

export const catalog: Product[] = [
  ...rankProducts,
  {
    id: "crate_mythic",
    category: "crate",
    name: "Llave Mythic",
    description: "Recompensas raras, cosmeticos y premios de alto valor.",
    priceUsd: 3.49,
    badge: "Mejor loot",
    gradientClass: "from-fuchsia-400/25 via-sky-400/15 to-transparent",
  },
  {
    id: "crate_season",
    category: "crate",
    name: "Llave de Temporada",
    description: "Drops limitados y premios rotativos del servidor.",
    priceUsd: 2.49,
    badge: "Limitada",
    gradientClass: "from-emerald-400/22 via-cyan-400/12 to-transparent",
  },
  {
    id: "crate_classic",
    category: "crate",
    name: "Llave Clasica",
    description: "Una mezcla confiable de cosmeticos y premios utiles.",
    priceUsd: 1.99,
    badge: "Popular",
    gradientClass: "from-amber-400/20 via-orange-400/12 to-transparent",
  },
  {
    id: "crate_builder",
    category: "crate",
    name: "Llave Builder",
    description: "Particulas, trails y recompensas para constructores.",
    priceUsd: 2.99,
    badge: "Estilo",
    gradientClass: "from-indigo-400/22 via-violet-400/12 to-transparent",
  },
  {
    id: "coins_10k",
    category: "coin",
    name: "10.000 Coins",
    description: "Recarga rapida para subastas, compras y cosmeticos.",
    priceUsd: 3.99,
    badge: "Recarga",
    gradientClass: "from-sky-400/22 via-indigo-400/12 to-transparent",
  },
  {
    id: "coins_50k",
    category: "coin",
    name: "50.000 Coins",
    description: "El punto ideal para bundles y compras frecuentes.",
    priceUsd: 14.99,
    badge: "+10% bonus",
    gradientClass: "from-violet-400/22 via-fuchsia-400/12 to-transparent",
  },
  {
    id: "coins_150k",
    category: "coin",
    name: "150.000 Coins",
    description: "Mejor valor para compras grandes dentro del servidor.",
    priceUsd: 39.99,
    badge: "+25% bonus",
    gradientClass: "from-emerald-400/20 via-cyan-400/12 to-transparent",
  },
];

export function formatUsd(amount: number) {
  const formatted = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 2,
  }).format(amount);

  return `${formatted} USD`;
}

export function getProductById(id: string) {
  return catalog.find((p) => p.id === id) ?? null;
}

export function getProductsByCategory(category: ProductCategory) {
  return catalog.filter((p) => p.category === category);
}
